// Binary Sensors
#define ARDUINOHOMELIB_USE_BINARY_SENSOR_MOTION

// Buttons
#define ARDUINOHOMELIB_USE_BUTTON_MOMENTARY

// Lights
#define ARDUINOHOMELIB_USE_LIGHT_FASTLED

// Sensors
#define ARDUINOHOMELIB_USE_SENSOR_DALLAS
#define ARDUINOHOMELIB_USE_SENSOR_DHT
#define ARDUINOHOMELIB_USE_SENSOR_MAX31856
#define ARDUINOHOMELIB_USE_SENSOR_MAX6675
#define ARDUINOHOMELIB_USE_SENSOR_TEMT6000

// Switch
#define ARDUINOHOMELIB_USE_SWITCH
#define ARDUINOHOMELIB_USE_SWITCH_I2C